language: python

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      python: 3.7.2
      services:
      - docker
      env: CIBW_BEFORE_BUILD="rm -rf build/"
    - os: osx
      language: generic

install:
  - pip3 install -U setuptools twine wheel cibuildwheel

script:
  - cd apsw
  - sed -i'' -e 's/name="apsw"/name="apsw_wheels"/' setup.py
  - sed -i'' -e 's/build_enable_all_extensions=False/build_enable_all_extensions=True/' setup.py
  - python3 setup.py fetch --all
  - sed -i'' -e 's/-r1/-r2/' src/apswversion.h
  - python3 setup.py sdist
  - cibuildwheel --output-dir /tmp/wheelhouse

deploy:
  provider: script
  script: "twine upload --skip-existing /tmp/wheelhouse/* dist/*"
  skip_cleanup: true
  on:
    tags: true
